### PR TITLE
Add nix flake and direnv

### PR DESCRIPTION
**Pull request by Kloenk**
This installes a rust compiler via nix if the user has nix and direnv installed.
This also adds a rust package and a rust check

### CODE REVIEW

**Comment by SZenglein** [comment]
Hi, Thanks for your PR!

At the moment, we're not sure if we want to commit Cargo.lock to the repo. I'll consider it.

While I have heard of nix and like the concept, I have not yet used it personally.  
Could you explain the benefits and why it must be included in the project repository? It might help if you can point to some other larger rust project where nix and direnv is provided.

In general I find it quite easy to build with cargo, and we don't use any (C) dependencies that are difficult to build.  
Does nix add something substantial? Is it publishing the smp-tool demo as a nixpkg or is it purely for a dev-environment?

**Comment by Kloenk** [comment]
I added the Cargo.lock, as per recommendations I found cargo.lock is not of interest for libraries, but as soon as there are tests or binaries (which are in a different package here) it is recommended and makes ci easier. Also nix uses this cargo.lock to build the dependency graph for the package the flake introduces. 

The initial benefit is for me, as I dont have cargo installed on my system, but load it on a per project basis via direnv and nix flakes. But also this exposes a package, which then can run without explicitly first downloading the repo (`nix run github:sysbadge/smp-rs/kloenk/nix/flake -- --help`, path will change when merged). This package is also exposed via an overlay, so it makes it easier to pull it into other nix based projects as a dependency. Furthermore this addes a CI capable check (`nix flake check`) that does a rustfmt and nixfmt check on the code and build the package and executes the testes.

**Comment by SZenglein** [comment]
Latest official stance I know of is this: https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html, which is basically there is no recommendation. But let's ignore Cargo.lock for now.

I can see how it's convenient, but I don't really see why nix in particular should be supported. I don't want to add package definitions and scripts for all other package managers.   
Sure, nix offers some nifty features that can be used in the CI, but nothing cargo doesn't already support.

As for the development setup, I feel like every project repo is the wrong place to add these configurations. I would bet most rustaceans have installed rust using rustup.

FWIW, you can already run cargo install on a git repo URL.

Do you see any way those definitions could live in a different repo?

**Comment by Kloenk** [comment]
Less convenient because I can't directly import the cargo.lock but yes, it can also work outside the repo

**Pull request closed without merging**
